# Generated by Django 4.2.3 on 2023-07-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0002_rename_park_name_site_park_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitebooking',
            old_name='site',
            new_name='site_id',
        ),
    ]
