# Generated by Django 4.2.3 on 2023-08-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0004_site_electicity_site_sewage_site_site_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='electicity',
            new_name='electricity',
        ),
    ]
