# Generated by Django 4.2.3 on 2023-08-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0006_siteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='photo',
            field=models.ImageField(default=0, upload_to='../assets/site-images'),
            preserve_default=False,
        ),
    ]
