# Generated by Django 4.2.3 on 2023-08-16 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0009_sitebooking_email_sitebooking_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='photo',
        ),
    ]
