# Generated by Django 4.2.3 on 2023-08-21 17:36

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0013_alter_site_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1280, 720], upload_to='./assets/site-images'),
        ),
    ]
