# Generated by Django 4.2.3 on 2023-08-21 17:44

import booking_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0014_alter_siteimage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='photo',
            field=models.ImageField(upload_to='./assets/site-images', validators=[booking_api.validators.image_validator]),
        ),
    ]
