# Generated by Django 4.2.3 on 2023-08-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0019_amenities_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
            preserve_default=False,
        ),
    ]
