# Generated by Django 4.2.3 on 2023-09-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0020_park_latitude_park_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='park',
            name='latitude',
            field=models.DecimalField(decimal_places=13, max_digits=30),
        ),
        migrations.AlterField(
            model_name='park',
            name='longitude',
            field=models.DecimalField(decimal_places=13, max_digits=30),
        ),
    ]
