# Generated by Django 4.2.3 on 2023-07-27 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_park_site_sitebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebooking',
            name='park',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_api.park'),
            preserve_default=False,
        ),
    ]
