# Generated by Django 4.2.3 on 2023-07-29 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='park_name',
            new_name='park_id',
        ),
    ]
