# Generated by Django 4.2.3 on 2023-08-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0007_site_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='photo',
            field=models.ImageField(upload_to='./assets/site-images'),
        ),
    ]
