# Generated by Django 4.2.3 on 2023-08-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0008_alter_site_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebooking',
            name='email',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitebooking',
            name='first_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitebooking',
            name='last_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
