# Generated by Django 4.2.3 on 2023-08-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0010_remove_site_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='thumbnail',
            field=models.ImageField(default=0, upload_to='./assets/thumbnails'),
            preserve_default=False,
        ),
    ]
