# Generated by Django 4.2.3 on 2023-08-23 18:35

import booking_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0016_amenities_remove_site_electricity_remove_site_sewage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='city',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='logo',
            field=models.ImageField(default=0, upload_to='./assets/park/logo', validators=[booking_api.validators.logo_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='province',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='park',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
