# Generated by Django 4.2.3 on 2023-08-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0017_park_city_park_logo_park_province_alter_park_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='icon',
            field=models.ImageField(default=0, upload_to='./assets/amenities'),
            preserve_default=False,
        ),
    ]
